<?php
/**
 * @file
 * Code for the Dir feature.
 */

include_once 'dir.features.inc';

// -----------------------------------------------------------------------------
// General hook

/**
 * Implements hook_ctools_plugin_directory().
 */
function dir_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return $owner . '/' . $plugin_type;
  }
}

// -----------------------------------------------------------------------------
// EntityMetadataWrapper property callback

// -----------------
// dir_link property

/**
 * Helper function to generate the roles property info.
 */
function dir_link_roles_entity_property_info() {
  $info = array();
  $entity_info = entity_get_info('dir_role');
  foreach ($entity_info['bundles'] as $bundle => $bundle_info) {
    $info[$bundle] = array(
      'label' => $bundle_info['label'],
      'description' => t('@role is a role of link', array('@role' => $bundle_info['label'])),
      'type' => 'dir_role',
    );
  }

  return $info;
}

/**
 * 'getter callback' for dir_link roles property.
 */
function dir_link_roles_entity_property_getter($data, array $options, $name, $type, $info) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'dir_role')
    ->propertyCondition('link', $data->id);
  $result = $query->execute();

  return _dir_link_roles_entity_property_getter($result['dir_role']);
}

/**
 * Helper function to prepare the return.
 */
function _dir_link_roles_entity_property_getter($result) {
  // Prepare the skeloton array.
  $entity_info = entity_get_info('dir_role');
  $roles = array_fill_keys(array_keys($entity_info['bundles']), NULL);
  // Fill the values
  foreach ($result as $role) {
    $roles[$role->type] = $role->id;
  }

  return $roles;
}

// ----------------------
// dir_container property

/**
 * 'getter callback' for dir_container category parent property.
 */
function dir_container_parent_entity_property_getter($data, array $options, $name, $type, $info) {
  // Just a mirror of field_dir_category_parent.
  // @todo May have issue, wait to check.
  return entity_metadata_field_property_get($data, $options, 'field_dir_category_parent', $type, $info);
}

/**
 * 'getter callback' for dir_container category child property.
 */
function dir_container_child_entity_property_getter($data, array $options, $name, $type, $info) {
  return KtoolsEntityField::entityreferenceRevertEntities('field_dir_category_parent', $data->id, 'dir_container', $info['langcode']);
}
